#!/usr/bin/env bun

import path from "path"

type Arch = "x64" | "arm64"
type Libc = "glibc" | "musl"

type Release = {
  tag_name: string
  assets: {
    name: string
    browser_download_url: string
    digest?: string
  }[]
}

const dir = import.meta.dir

const help = `Usage: bun ./generate.ts [options]

Options:
  --repo <owner/name>  GitHub repo (default: anomalyco/opencode)
  --tag <tag>          Release tag to pin (default: latest)
  --arch <arch>        x64 or arm64 (default: host arch)
  --libc <libc>        glibc or musl (default: glibc)
  --baseline           Use baseline x64 binary
  --template <path>    Template Dockerfile (default: ./Dockerfile)
  --output <path>      Generated Dockerfile (default: ./Dockerfile.generated)
  --image <name>       Docker image name to print
  -h, --help           Show this help
`

const args = process.argv.slice(2)

function fail(msg: string): never {
  console.error(msg)
  process.exit(1)
}

function host(): Arch {
  if (process.arch === "x64") return "x64"
  if (process.arch === "arm64") return "arm64"
  return fail(`unsupported host arch: ${process.arch}`)
}

function take(flag: string) {
  const i = args.indexOf(flag)
  if (i === -1) return
  const val = args[i + 1]
  if (!val || val.startsWith("-")) fail(`missing value for ${flag}`)
  return val
}

function asset(arch: Arch, libc: Libc, baseline: boolean) {
  return (
    ["opencode-linux", arch, baseline ? "baseline" : undefined, libc === "musl" ? "musl" : undefined]
      .filter(Boolean)
      .join("-") + ".tar.gz"
  )
}

if (args.includes("-h") || args.includes("--help")) {
  console.log(help)
  process.exit(0)
}

const repo = take("--repo") ?? "anomalyco/opencode"
const tag = take("--tag") ?? "latest"
const arch = (take("--arch") ?? host()) as Arch
const libc = (take("--libc") ?? "glibc") as Libc
const baseline = args.includes("--baseline")
const tpl = path.resolve(dir, take("--template") ?? "./Dockerfile")
const out = path.resolve(dir, take("--output") ?? "./Dockerfile.generated")
const img = take("--image") ?? `${repo.split("/").at(-1) ?? "opencode"}-dev:${tag.replaceAll("/", "-")}`

if (!["x64", "arm64"].includes(arch)) fail(`unsupported arch: ${arch}`)
if (!["glibc", "musl"].includes(libc)) fail(`unsupported libc: ${libc}`)
if (baseline && arch !== "x64") fail("--baseline is only supported for x64")

const file = asset(arch, libc, baseline)
const api =
  tag === "latest"
    ? `https://api.github.com/repos/${repo}/releases/latest`
    : `https://api.github.com/repos/${repo}/releases/tags/${tag}`

const res = await fetch(api, {
  headers: {
    accept: "application/vnd.github+json",
    "user-agent": "docker-dev-generator",
  },
})

if (!res.ok) fail(`failed to fetch release ${tag} from ${repo}: ${res.status} ${res.statusText}`)

const rel = (await res.json()) as Release
const hit = rel.assets.find((item) => item.name === file)

if (!hit) {
  fail(`release ${rel.tag_name} in ${repo} does not include ${file}`)
}

const sum = hit.digest?.startsWith("sha256:") ? hit.digest.slice(7) : ""
const src = await Bun.file(tpl).text()
const dst = src
  .replace(/^ARG OPENCODE_TAG=.*$/m, `ARG OPENCODE_TAG=${rel.tag_name}`)
  .replace(/^ARG OPENCODE_ASSET=.*$/m, `ARG OPENCODE_ASSET=${file}`)
  .replace(/^ARG OPENCODE_URL=.*$/m, `ARG OPENCODE_URL=${hit.browser_download_url}`)
  .replace(/^ARG OPENCODE_SHA256=.*$/m, `ARG OPENCODE_SHA256=${sum}`)

await Bun.write(
  out,
  ["# Generated by ./generate.ts", `# Repo: ${repo}`, `# Release: ${rel.tag_name}`, `# Asset: ${file}`, "", dst].join(
    "\n",
  ),
)

console.log(`wrote ${path.relative(dir, out) || path.basename(out)}`)
console.log(`repo: ${repo}`)
console.log(`release: ${rel.tag_name}`)
console.log(`asset: ${file}`)
console.log(`url: ${hit.browser_download_url}`)
console.log("")
console.log(`docker build -f ${path.relative(process.cwd(), out)} -t ${img} .`)
